pipeline {
    agent any
    tools{
  		 maven 'Maven'
  		 jdk 'jdk1.8.0_211'
  		 }
    stages {
        stage('---clean1---') {
            steps {
                bat "mvn clean"
            }
        }
        stage('--test1--') {
            steps {
                bat "mvn test"
            }
        }
        stage('--package1--') {
            steps {
                bat "mvn package"
            }
        }
    }
}